class_name Enums

enum Team {
	UNKNOWN = 0,
	ORDER = 1,
	CHAOS = 2,
	NEUTRAL = 3,
}

enum Lane {
	RIGHT = 0,
	CENTER = 1,
	LEFT = 2,
}

enum Pos {
	FOUNTAN = 0,
	HQ_TOWER_1 = 5,
	HQ_TOWER_2 = 4,
	BACK = 1,
	MIDDLE = 2,
	FRONT = 3,
}

enum MinionType {
	MELEE,
	ARCHER,
	CASTER,
	SUPER,
}

enum OrderType {
	NONE,
	MOVE_TO,
	ATTACK_TO,
	ATTACK_MOVE,
	TAUNT,
}

enum ReasonForTargetLoss {
	LOST_VISIBILITY,
	OTHER,
}

enum ReasonToTurnOffAA {
	IMMEDIATELY,
	TARGET_LOST,
	MOVING,
}

enum AIState {
	IDLE,
	SOFTATTACK,
	HARDATTACK,
	ATTACKMOVE,
	STANDING,
	MOVE,
	#GUARD,
	#ATTACK,
	#RETREAT,
	HARDIDLE,
	#HARDIDLE_ATTACKING,
	TAUNTED,
	#ATTACKMOVE_ATTACKING,
	FEARED,
	CHARMED,
	FLEEING,
	ATTACK_GOING_TO_LAST_KNOWN_LOCATION,
	HALTED,
	#SIEGEATTACK,
	#LAST_NONPET_STATE,
	#ATTACK_HERO,
	#FOLLOW,
	#FOLLOW_HERO,
	#PET_ATTACK,
	#PET_ATTACKMOVE,
	#PET_ATTACKMOVE_ATTACKING,
	#PET_HARDATTACK,
	#PET_HARDIDLE,
	#PET_HARDIDLE_ATTACKING,
	#PET_HARDMOVE,
	#PET_HARDRETURN,
	#PET_HARDSTOP,
	#PET_HOLDPOSITION,
	#PET_HOLDPOSITION_ATTACKING,
	#PET_IDLE,
	#PET_MOVE,
	#PET_RETURN,
	#PET_RETURN_ATTACKING,
	#PET_SPAWNING,
	#SHOP,
	#STOP,
}

enum BuffAddType
{
	UNDEFINED,
	REPLACE_EXISTING,
	RENEW_EXISTING,
	STACKS_AND_RENEWS,
	STACKS_AND_CONTINUE,
	STACKS_AND_OVERLAPS,
}

enum BuffType {
	UNDEFINED = 0,
	INTERNAL = 1 << 0,
	AURA = 1 << 1,
	COMBAT_ENCHANCER = 1 << 2,
	COMBAT_DEHANCER = 1 << 3,
	#SPELL_SHIELD = 1 << 4,
	STUN = 1 << 5,
	INVISIBILITY = 1 << 6,
	SILENCE = 1 << 7,
	TAUNT = 1 << 8,
	POLYMORPH = 1 << 9,
	SLOW = 1 << 10,
	SNARE = 1 << 11,
	DAMAGE = 1 << 12,
	HEAL = 1 << 13,
	HASTE = 1 << 14,
	SPELL_IMMUNITY = 1 << 15,
	PHYSICAL_IMMUNITY = 1 << 16,
	INVULNERABILITY = 1 << 17,
	SLEEP = 1 << 18,
	#NEAR_SIGHT = 1 << 19,
	#FRENZY = 1 << 20,
	FEAR = 1 << 21,
	CHARM = 1 << 22,
	POISON = 1 << 23,
	SUPPRESSION = 1 << 24,
	BLIND = 1 << 25,
	COUNTER = 1 << 26,
	SHRED = 1 << 27,
	#FLEE = 1 << 28,
	#KNOCKUP = 1 << 29,
	#KNOCKBACK = 1 << 30,
	#DISARM = 1 << 31,

	NEGATIVE = \
		INTERNAL |\
		#AURA |\
		#COMBAT_ENCHANCER |\
		COMBAT_DEHANCER |\
		#SPELL_SHIELD |\
		STUN |\
		#INVISIBILITY |\
		SILENCE |\
		TAUNT |\
		POLYMORPH |\
		SLOW |\
		SNARE |\
		DAMAGE |\
		#HEAL |\
		#HASTE |\
		#SPELL_IMMUNITY |\
		#PHYSICAL_IMMUNITY |\
		#INVULNERABILITY |\
		SLEEP |\
		#NEAR_SIGHT |\
		#FRENZY |\
		FEAR |\
		CHARM |\
		POISON |\
		SUPPRESSION |\
		BLIND |\
		#COUNTER |\
		SHRED |\
		#FLEE |\
		#KNOCKUP |\
		#KNOCKBACK |\
		#DISARM |\
		0,
}

enum DamageType
{
	PHYSICAL,
	MAGICAL,
	TRUE,
}

enum DamageSource
{
	RAW,
	INTERNALRAW,
	PERIODIC,
	PROC,
	REACTIVE,
	ONDEATH,
	SPELL,
	ATTACK,
	DEFAULT,
	SPELLAOE,
	SPELLPERSIST,
	PET,
}

enum HitResult
{
	NORMAL,
	CRITICAL,
	DODGE,
	MISS,
}

enum EffCreate
{
	NONE,
	UPDATE_ORIENTATION
}

enum TargetingType
{
	SELF = 0,
	TARGET = 1,
	AREA = 2,
	CONE = 3,
	SELF_AOE = 4,
	TARGET_OR_LOCATION = 5,
	LOCATION = 6,
	DIRECTION = 7,
	#DRAG_DIRECTION = 8,
	#LINE_TARGET_TO_CASTER = 9,
	#OFFSET_AOE = 9,
	#OFFSET_LOCATION = 10,
}

enum CastType
{
	INSTANT,
	TARGET_MISSILE,
	CHAIN_MISSILE,
	ARC_MISSILE,
	CIRCLE_MISSILE,
}

enum SpellFlags
{
	NONE = 0,
	AUTO_CAST = 1 << 1,
	INSTANT_CAST = 1 << 2,
	PERSIST_THROUGH_DEATH = 1 << 3,
	NON_DISPELLABLE = 1 << 4,
	NO_CLICK = 1 << 5,
	AFFECT_IMPORTANT_BOT_TARGETS = 1 << 6,
	ALLOW_WHILE_TAUNTED = 1 << 7,
	NOT_AFFECT_ZOMBIE = 1 << 8,
	AFFECT_UNTARGETABLE = 1 << 9,
	AFFECT_ENEMIES = 1 << 10,
	AFFECT_FRIENDS = 1 << 11,
	AFFECT_NEUTRAL = 1 << 14,
	AFFECT_BUILDINGS = 1 << 12,
	AFFECT_MINIONS = 1 << 15,
	AFFECT_HEROES = 1 << 16,
	AFFECT_TURRETS = 1 << 17,
	NOT_AFFECT_SELF = 1 << 13,
	ALWAYS_SELF = 1 << 18,
	AFFECT_DEAD = 1 << 19,
	AFFECT_NOT_PET = 1 << 20,
	AFFECT_BARRACK_ONLY = 1 << 21,
	IGNORE_VISIBILITY_CHECK = 1 << 22,
	NON_TARGETABLE_ALLY = 1 << 23,
	NON_TARGETABLE_ENEMY = 1 << 24,
	TARGETABLE_TO_ALL = 1 << 25,
	AFFECT_WARDS = 1 << 26,
	AFFECT_USEABLE = 1 << 27,
	IGNORE_ALLY_MINION = 1 << 28,
	IGNORE_ENEMY_MINION = 1 << 29,
	IGNORE_LANE_MINION = 1 << 30,
	IGNORE_CLONES = 1 << 31,

	#DEFAULT = AFFECT_ENEMIES | AFFECT_FRIENDS | AFFECT_MINIONS | AFFECT_HEROES | AFFECT_TURRETS,
	DEFAULT = AFFECT_ENEMIES | AFFECT_NEUTRAL | AFFECT_MINIONS | AFFECT_HEROES,
}

enum SpellSelectPref
{
	NONE, FOE, FRIEND,
}

enum PARType
{
	MANA,
	ENERGY,
	NONE,
	SHIELD,
	BATTLEFURY,
	DRAGONFURY,
	RAGE,
	HEAT,
	GNARFURY,
	FEROCITY,
	BLOODWELL,
	WIND,
	OTHER,
}

enum EmoteType {
	NONE, JOKE, TAUNT, DANCE, LAUGH
}
static func EmoteType_to_string(i: int) -> String:
	return str(EmoteType.keys()[i]).to_pascal_case()

enum ForceMovementType
{
	FURTHEST_WITHIN_RANGE,
	FIRST_COLLISION_HIT,
	GET_NEAREST_IN_RANGE,
	GET_NEAREST_IN_RANGE_INCLUDE_UNITS,
	FIRST_WALL_HIT,
}

enum ForceMovementOrdersType
{
	CANCEL_ORDER,
	POSTPONE_CURRENT_ORDER,
}

enum ForceMovementOrdersFacing
{
	FACE_MOVEMENT_DIRECTION,
	KEEP_CURRENT_FACING,
}

enum SpawnType
{
	NONE,
    SPAWN_HQ,
    SPAWN_LOCATION,
    SPAWN_BARRACKS_LANE_R,
    SPAWN_BARRACKS_LANE_C,
    SPAWN_BARRACKS_LANE_L,
    SPAWN_DAMPENER_LANE_R,
    SPAWN_DAMPENER_LANE_C,
    SPAWN_DAMPENER_LANE_L,
    SPAWN_SHOP,
}

enum ChannelingStopSource
{
    NOT_CANCELLED,
    TIME_COMPLETED,
    ANIMATION,
    LOST_TARGET,
    STUNNED_OR_SILENCED_OR_TAUNTED,
    CHANNELING_CONDITION,
    DIE,
    HERO_REINCARNATE,
    MOVE,
    ATTACK,
    CASTING,
}

enum ChannelingStopCondition
{
    NOT_CANCELLED,
    SUCCESS,
    CANCEL,
}